"""
Django settings for BookingSystem205 project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

FLASK_API_URL = os.environ.get("FLASK_API_URL", "http://localhost:5000")


# -------------------------
# SECURITY / ENVIRONMENT
# -------------------------
SECRET_KEY = 'django-insecure-)2qx2m&_y0&!@_u0k(c&03hzx^)kznw%)nsbw!24ud$$3)2-t^'

DEBUG = False

# Adjust for EB host
ALLOWED_HOSTS = [
    'Django-Front-env-1.eba-sdhq4nhx.ap-southeast-2.elasticbeanstalk.com',
    '*'
]


# -------------------------
# APPLICATIONS
# -------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'App'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BookingSystem205.urls'


# -------------------------
# TEMPLATES
# -------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'App' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BookingSystem205.wsgi.application'


# -------------------------
# DATABASE
# -------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': '502-server',
        'USER': 'postgres',
        'PASSWORD': '1',
        'HOST': 'localhost',   # OK to keep for now
        'PORT': '5432',
    }
}


# -------------------------
# AUTH / SECURITY
# -------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# -------------------------
# INTERNATIONALIZATION
# -------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# -------------------------
# STATIC & MEDIA FILES
# -------------------------
STATIC_URL = '/static/'

# Local static folder for development
STATICFILES_DIRS = [
    BASE_DIR / 'App' / 'static',
]

# Production static collection target folder
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# -------------------------
# MISC
# -------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
